# -*- coding: utf-8 -*-
"""
/***************************************************************************
 LallemandPlantCare
                                 A QGIS plugin
 Lallemand Plant Care
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-10-07
        copyright            : (C) 2023 by CamellOnCase
        email                : camelloncase@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load LallemandPlantCare class from file lallemand_plant_care.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .lallemand_plant_care import LallemandPlantCare
    return LallemandPlantCare(iface)
