# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ToolbarManager
                                 A QGIS plugin
 Lallemand Plant Care
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2023-10-07
        git sha              : $Format:%H$
        copyright            : (C) 2023 by CamellOnCase
        email                : camelloncase@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

from qgis.PyQt.QtCore import pyqtSlot
from qgis.PyQt.QtWidgets import QWidget
from qgis.core import QgsMapLayer

from .filter.filtering_dlg import FilteringPoints
from .geostatistics_trial.geostatistics_trial import GeostatisticsTrial
from .kriging.kriging_dlg import OrdinaryKriging
from .layer_manager.load_files_dlg import LoadFiles
from .lpc_team.farmer_manager import FarmerManager
from .lpc_team.lpc_team_manager import RegisterLpcTeam
from .report.report_dlg import StatisticsReport
from .toolbar.toolbar_form_base import Ui_Form
from .treatment.treatment_polygons_dlg import TreatmentPolygons
from .validation.validation_dlg import SamplingValidation
from ..core.algorithms.algorithm_runner import AlgorithmRunner
from ..core.constants import QGIS_TOC_GROUPS
from ..core.services.layer_service import LayerService


class ToolbarManager(QWidget, Ui_Form):
    def __init__(self, iface, toolbar=None):
        """Constructor."""
        super(ToolbarManager, self).__init__()
        self.setupUi(self)
        self.iface = iface
        self.toolbar = toolbar
        self.actions = list()
        self.layerService = LayerService()
        self.algRunner = AlgorithmRunner()
        self.splitter.hide()
        self.createTrialPushButton.clicked.connect(self.createTrialProject)
        self.loadFilePushButton.clicked.connect(self.loadFiles)
        self.lpcTeamPushButton.clicked.connect(self.manageLpcTeam)
        self.farmerPushButton.clicked.connect(self.manageFarmer)
        self.treatmentPushButton.clicked.connect(self.treatments)
        self.filterPushButton.clicked.connect(self.filtering)
        self.krigingPushButton.clicked.connect(self.ordinaryKriging)
        self.samplingValidationPushButton.clicked.connect(self.validation)
        self.clearStructurePushButton.clicked.connect(self.clearTreeView)
        self.reportPushButton.clicked.connect(self.getReport)
        self.mapsPushButton.clicked.connect(self.composer)
        self.exportMapPushButton.clicked.connect(self.exportMaps)
        self.samplingPushButton.clicked.connect(self.sampling)
        self.errorCompensationPushButton.clicked.connect(self.errorCompensation)
        self.gainSurfacePushButton.clicked.connect(self.gainSurface)
        self.presentationPushButton.clicked.connect(self.getPresentation)

    def unload(self):
        pass

    @pyqtSlot(bool, name="on_showToolbarPushButton_toggled")
    def toggleToolbar(self, toggled=None):
        """
        Shows/Hides the toolbar showAccountPushButton
        """
        if toggled is None:
            toggled = self.showToolbarPushButton.isChecked()
        if toggled:
            self.splitter.show()
        else:
            self.splitter.hide()

    @staticmethod
    def createTrialProject():
        """
        Shows the dialog that loads layers from server
        """
        dlg = GeostatisticsTrial()
        dlg.show()
        result = dlg.exec_()
        if result:
            pass

    def loadFiles(self):
        project = self.layerService.checkForSavedProject()
        if project:
            dlg = LoadFiles(project)
            dlg.show()
            result = dlg.exec_()
            if result:
                pass

    @staticmethod
    def manageLpcTeam():
        dlg = RegisterLpcTeam()
        dlg.show()
        result = dlg.exec_()
        if result:
            pass

    @staticmethod
    def manageFarmer():
        dlg = FarmerManager()
        dlg.show()
        result = dlg.exec_()
        if result:
            pass

    def treatments(self):
        project = self.layerService.checkForSavedProject()

        if project:
            layer = project.mapLayersByName('GPS_points')[0]
            epsg = str()
            reproject: bool() = None
            parameters = {'GPS_POINTS_LAYER': layer,
                          'REPROJECT': '',
                          'CRS': '',
                          'SORTING_FIELD': 'ID',
                          'METHOD': 1,
                          'BORDER_SIZE': 10,
                          'BOUNDARY': True}

            if layer and layer.crs().isGeographic():
                crsOperations = self.layerService.getSuggestedCrs(layer)
                reproject = True
                epsg = crsOperations[2]

            self.algRunner.runTreatmentPolygons(epsg, reproject, parameters)

    def filtering(self):

        project = self.layerService.checkForSavedProject()
        layers = project.mapLayers().values()
        harvesterLayer = self.layerService.filterByLayerName(list(layers),
                                                             ['GPS', 'T1', 'T2', 'Gain', 'Yield'],
                                                             inverse=True)
        if project:
            parameters = {
                'HARVESTER_POINTS_LAYER': harvesterLayer[0],
                'REPROJECT': True,
                'ID_FIELD': '',
                'YIELD_FIELD': '',
                'TREATMENT_POLYGONS': '',
                'TREATMENT_ID_FIELD': '',
                'BOUNDARY_POLYGON': '',
                'TARGET_PROJECTION': 0, 'DATE_COLUMN': 0}
            self.algRunner.runHarvesterFilter(parameters)

    def ordinaryKriging(self):
        project = self.layerService.checkForSavedProject()
        if project:
            dlg = OrdinaryKriging(self.iface, project)
            dlg.show()
            result = dlg.exec_()
            if result:
                pass

    def validation(self):
        project = self.layerService.checkForSavedProject()
        if project:
            parameters = {
                'GRID': '',
                'VALIDATION_FIELD': '',
                'VALIDATION_LAYER': ''
            }
            self.algRunner.runCalculateError(parameters)

    def errorCompensation(self):
        project = self.layerService.checkForSavedProject()
        if project:
            parameters = {
                'POINTS': True,
                'T1_80_RASTER': '',
                'T1_ERROR_RASTER': '',
                'T2_80_RASTER': '',
                'T2_ERROR_RASTER': ''
            }
            self.algRunner.runErrorCompensation(parameters)

    def gainSurface(self):
        project = self.layerService.checkForSavedProject()
        if project:
            parameters = {
                'POINTS': True,
                'T1_RASTER': '',
                'T2_RASTER': ''
            }
            self.algRunner.runGainSurface(parameters)

    def clearTreeView(self):
        project = self.layerService.checkForSavedProject()
        root = project.layerTreeRoot()
        if project:
            for index, layer in enumerate(self.iface.mapCanvas().layers()):
                if layer.type() == QgsMapLayer.RasterLayer:
                    layer_node = root.findLayer(layer.id())

                    if 'validation' in layer.name().split('_'):
                        self.layerService.applySymbology(layer, '', raster=True)
                        self.layerService.addMapLayer(layer, QGIS_TOC_GROUPS[5])
                    else:
                        self.layerService.applySymbology(layer, '', raster=True)
                        self.layerService.addMapLayer(layer, QGIS_TOC_GROUPS[3])

                    parent = layer_node.parent()
                    parent.removeChildNode(layer_node)

    def getReport(self):
        project = self.layerService.checkForSavedProject()
        if project:
            parameters = {
                'GAIN_POINTS': '',
                'OUTPUT': '',
                'T1_LAYER': '',
                'T1_SURFACE': '',
                'T2_LAYER': '',
                'T2_SURFACE': '',
                'TRIAL_NAME': '',
                'YIELD': ''
            }
            self.algRunner.runCreateReport(parameters, project)

    def composer(self):
        project = self.layerService.checkForSavedProject()
        if project:
            self.algRunner.runLoadComposerTemplates(project)

    def exportMaps(self):
        project = self.layerService.checkForSavedProject()
        if project:
            self.algRunner.runExportMaps(project)

    def sampling(self):
        project = self.layerService.checkForSavedProject()
        if project:
            self.algRunner.runCreateSampleLayers()

    def getPresentation(self):
        project = self.layerService.checkForSavedProject()
        if project:
            parameters = {
                'GAIN_POINTS': '',
                'OUTPUT': '',
                'T1_SURFACE': '',
                'T1_VALIDATION': '',
                'T2_SURFACE': '',
                'T2_VALIDATION': '',
                'TRIAL_NAME': '',
                'YIELD_FIELD': ''
            }
            self.algRunner.runCreatePresentation(parameters, project)

