# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GeostatisticsTrial
                                 A QGIS plugin
 Lallemand Plant Care
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-10-04
        git sha              : $Format:%H$
        copyright            : (C) 2023 by CamellOnCase
        email                : camelloncase@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import processing

from qgis.core import QgsCoordinateReferenceSystem
from qgis.PyQt.Qt import QObject


class AlgorithmRunner(QObject):

    def __init__(self, iface=None):
        super(AlgorithmRunner, self).__init__()
        self.iface = iface
        if iface:
            self.canvas = iface.mapCanvas()

    @staticmethod
    def runWaypointsPolygonsBuilder(layer, method, sorting, context=None, feedback=None, output_layer=None):
        output_layer = 'memory:' if output_layer is None else output_layer
        parameters = {
            'Waypoints': layer, 'Methode': method, 'Variable_ordonnee': sorting, 'Polygones_traitement': output_layer
        }
        output = processing.run('r:Waypoints_Polygons_builder', parameters, context=context, feedback=feedback)
        print(output)
        return output['Polygones_traitement']

    @staticmethod
    def runReprojectLayer(layer, targetCrs, operation=None, context=None, feedback=None, output_layer=None):
        output_layer = 'memory:' if output_layer is None else output_layer
        parameters = {
            'INPUT': layer, 'TARGET_CRS': QgsCoordinateReferenceSystem(targetCrs),
            'OPERATION': operation, 'OUTPUT': output_layer
        }
        output = processing.run('native:reprojectlayer', parameters, context=context, feedback=feedback)

        return output['OUTPUT']
