# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PresentationProcessingAlgorithm
                                 A QGIS plugin
 Lallemand Plant Care
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-05-01
        git sha              : $Format:%H$
        copyright            : (C) 2023 by CamellOnCase
        email                : camelloncase@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import json
import os


class ProcessingAlgorithmHelpCreator(object):

    @staticmethod
    def shortHelpString(algorithm_name):
        name = algorithm_name.split('_')
        algorithmName = name[0] + ''.join(word for word in name[1:])
        html_path = "{}/{}.html".format(os.path.join(os.path.dirname(os.path.abspath(__file__)), 'html'), algorithmName)

        html_file = open(html_path, "r")
        html_string = html_file.read()

        return html_string
