# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'toolbar_manager.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class ToolbarManagerUiForm(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(471, 36)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(0, 20))
        Form.setMaximumSize(QtCore.QSize(471, 50))
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(2, 0, 2, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.showToolbarPushButton = QtWidgets.QPushButton(Form)
        self.showToolbarPushButton.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.showToolbarPushButton.sizePolicy().hasHeightForWidth())
        self.showToolbarPushButton.setSizePolicy(sizePolicy)
        self.showToolbarPushButton.setMinimumSize(QtCore.QSize(30, 30))
        self.showToolbarPushButton.setMaximumSize(QtCore.QSize(30, 30))
        self.showToolbarPushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/plugins/crop_analysis_environment/icons/lallemand.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.showToolbarPushButton.setIcon(icon)
        self.showToolbarPushButton.setIconSize(QtCore.QSize(24, 24))
        self.showToolbarPushButton.setCheckable(True)
        self.showToolbarPushButton.setObjectName("showToolbarPushButton")
        self.horizontalLayout.addWidget(self.showToolbarPushButton)
        spacerItem = QtWidgets.QSpacerItem(15, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.splitter = QtWidgets.QSplitter(Form)
        self.splitter.setMinimumSize(QtCore.QSize(0, 0))
        self.splitter.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.splitter)
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.createTrialPushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.createTrialPushButton.setMinimumSize(QtCore.QSize(0, 0))
        self.createTrialPushButton.setMaximumSize(QtCore.QSize(30, 30))
        self.createTrialPushButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/plugins/crop_analysis_environment/icons/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.createTrialPushButton.setIcon(icon1)
        self.createTrialPushButton.setIconSize(QtCore.QSize(20, 20))
        self.createTrialPushButton.setObjectName("createTrialPushButton")
        self.horizontalLayout_2.addWidget(self.createTrialPushButton)
        self.loadFilePushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.loadFilePushButton.setMaximumSize(QtCore.QSize(30, 30))
        self.loadFilePushButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/plugins/crop_analysis_environment/icons/load.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.loadFilePushButton.setIcon(icon2)
        self.loadFilePushButton.setIconSize(QtCore.QSize(20, 20))
        self.loadFilePushButton.setObjectName("loadFilePushButton")
        self.horizontalLayout_2.addWidget(self.loadFilePushButton)
        self.report_pb = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.report_pb.setMaximumSize(QtCore.QSize(30, 30))
        self.report_pb.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/plugins/crop_analysis_environment/icons/report.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.report_pb.setIcon(icon3)
        self.report_pb.setIconSize(QtCore.QSize(20, 20))
        self.report_pb.setObjectName("report_pb")
        self.horizontalLayout_2.addWidget(self.report_pb)
        spacerItem1 = QtWidgets.QSpacerItem(300, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.horizontalLayout.addWidget(self.splitter)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
